[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ipiranga"
authors = [{name = "Alvan", email = "xavier@ipiranga"}]
dynamic = ["version", "description"]
